# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/GerenseaWoldemichael/450ffa09409614a23c1ccc7b40364afc/untitled1.ipynb
"""

# library
import pandas as pd
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
import matplotlib.pyplot as plt

# 1️⃣ Connect to Google Sheet
gc = gspread.service_account(filename="adept-sentinel-216305-83b690fc2154.json")
sh = gc.open("sales_data2") # Corrected sheet name, assuming 'sales_data2' based on previous cells
worksheet = sh.worksheet('Sheet1') # Use sh.worksheet instead of gc.worksheet

# 2️⃣ Read data
df = get_as_dataframe(worksheet)

# 3️⃣ Clean data
df = df.dropna()
df["Price"]=df["Price"].astype(float)
df["Quantity"]=df["Quantity"].astype(float)

# 4️⃣ Create revenue column
df["Revenue"]=df["Price"]*df["Quantity"]

# 5️⃣ Group by product and total revenue
revenue_summary = df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)

# 6️⃣ Optional: group by date for daily trend
daily_summary = df.groupby("Date")["Revenue"].sum()

# 7️⃣ Plot revenue trend
plt.figure(figsize=(4,2))
daily_summary.plot(kind="line", marker="o")
plt.title("Daily Revenue Trend")
plt.xlabel("Date")
plt.ylabel("Revenue")
plt.grid(False)
plt.savefig("daily_revenue_trend.png")

# 8️⃣ Write results back to Google Sheets
try:
    report_sheet = sh.worksheet("Revenue Report")
except:
    report_sheet = sh.add_worksheet(title="Revenue Report", rows="100", cols="20")

set_with_dataframe(report_sheet, revenue_summary.reset_index())

print("✅ Portfolio report updated!")